-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO I join REST_REVIEW R 
on I.REST_ID = R.REST_ID
WHERE I.ADDRESS like "서울%"
group by i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY ROUND(AVG(r.REVIEW_SCORE), 2) DESC, FAVORITES DESC;