-- 코드를 입력하세요
SELECT U.TITLE,R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,date_format(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD U join USED_GOODS_REPLY R
ON U.BOARD_ID= R.BOARD_ID
where SUBSTR(U.CREATED_DATE,1,7) = '2022-10'
order by R.CREATED_DATE asc, U.TITLE ASC